# These need to be set to add the rtl_433 external component to ESPHome
# This currently ONLY works with ESP-32 boards
external_components:
  - source: github://juanboro/esphome-rtl_433-decoder
    components: [ rtl_433 ]

esphome:
  libraries:
    - rtl_433_Decoder_ESP=https://github.com/juanboro/rtl_433_Decoder_ESP.git
