substitutions:
  cs:   { number: 5, ignore_strapping_warning: true }   # CC1101 pin 4 (green)
  clk:  "18"  # CC1101 pin 5 (blue)
  mosi: "23"  # CC1101 pin 6 (purple)
  miso: "19"  # CC1101 pin 7 (grey)
  rx:   "32"  # CC1101 pin 3 (brown)
  tx:   "32"  # CC1101 pin 3 (brown)
  tx_rx_shared: "true"
  cc1101id: "mycc1101"  
  cc1101name: "CC1101"
  init_frequency_mhz: 433.92
  init_bw: 203
  includecontrols: false

packages:
  cc1101controls: !include { file: cc1101-controls.yaml, vars: {cc1101id: $cc1101id , use_extendend_controls: $includecontrols } }

spi:
  # these are the default VSPI pins to use on ESP32
  clk_pin: $clk    # CC1101 pin 5
  mosi_pin: $mosi  # CC1101 pin 6
  miso_pin: $miso  # CC1101 pin 7

cc1101:
  id: ${cc1101id}
  cs_pin: ${cs} # CC1101 pin 4
  frequency: ${init_frequency_mhz}MHz
  filter_length_ask_ook: 12dB

esphome:
  on_boot:
    - priority: -101.0
      then:
        - script.execute:
            # Set the initial bandwidth using custom script on boot (use recommended settings based on BW)
            id: ${cc1101id}_set_bw
            bw: ${init_bw}

remote_receiver:
  - id: ${cc1101id}_rf_receiver
    idle: 10ms # Adjust as needed
    filter: 20us # Some RF sources have pretty high BW - adjust as needed
    buffer_size: 4096 # This value is pretty large... default 10k is way too large
    pin:
      number: $rx
      allow_other_uses: true
      id: ${cc1101id}_gd0_recv
      mode:
        input: true
        output: true
        pullup: true
        open_drain: true

remote_transmitter:
  - id: ${cc1101id}_rf_transmitter
    pin:
      number: $tx
      allow_other_uses: ${tx_rx_shared}
      id: ${cc1101id}_gd0_xmit
      mode:
        input: true
        output: true
        pullup: true
        open_drain: true
    eot_level: false
    on_transmit:
      then:
        - cc1101.begin_tx:
            id: ${cc1101id}
    on_complete:
        - cc1101.set_idle:
            id: ${cc1101id}
        - remote_transmitter.digital_write:
            transmitter_id: ${cc1101id}_rf_transmitter
            value: true
        - cc1101.begin_rx:
            id: ${cc1101id}
    carrier_duty_percent: 100%
    non_blocking: true

# it's a good idea to turn off the CC1101 receiver when doing OTA updates
ota:
  platform: esphome
  on_begin:
    - lambda: id(${cc1101id}).set_idle();

